"use client";
import type { WidgetCatalogEntry } from "./types";
import {
  MrrCard, ArrCard, ActiveMembersCard, ChurnRateCard, ArpuCard, LtvCard,
  GrossMarginCard, PaymentIssuesCard, RevenueTotalCard, RefundRateCard,
  VisitorsBreakdownCard, MrrSparkline, ChurnGauge, ConversionGauge, MonthlyGoalsProgress,
  ChurnZoneGauge, ConversionZoneGauge, RevenueBigNumber, MrrThermometer,
  PromotionsAreaCard, CompetitorsAreaCard, GrowthTrioCard, GoalAchievementRing,
  MembersQuadrantCard, ProductTrendList, FeatureUsageProgress,
  SubscriptionStatusStrip, YoYHistoryList,
} from "./MetricCards";
import {
  RevenueAreaChart, LineRevenueChart, VerticalBarChart, HorizontalBarsChart,
  GroupedBarChart, ChurnDonut, ProductMixPie, SalesFunnelChart, FunnelStepsChart,
  YoYCompareBars, TargetLineChart, DonutWithCenterStat, TopProductBars, MiniDonutRow,
  StackedVerticalBarsChart, StackedHorizontalBarsChart, BubbleScatterChart,
  ComboBarLineChart, WaterfallChart,
  HistogramChart, ChurnReasonDonut,
} from "./DataCharts";
import {
  CohortRetentionTable, TopTradesTable, LatestOrdersTable, SalesPerformanceTable,
  SubscriptionStatusBreakdown, DealsLeaderboard,
} from "./Tables";

export const WIDGET_REGISTRY: WidgetCatalogEntry[] = [
  // ─── KENNZAHL ────────────────────────────────────────────────────────────
  {
    id: "kpi.mrr",
    title: "MRR",
    description: "Monthly Recurring Revenue — eine grosse Zahl + Delta-Pfeil.",
    category: "Kennzahl",
    defaultCols: 3,
    allowedCols: [3, 4, 6],
    inspiration: "Standard-SaaS-KPI-Card",
    render: (data) => <MrrCard data={data} />,
  },
  {
    id: "kpi.arr",
    title: "ARR (Annual Run-Rate)",
    description: "Hochgerechnete Jahres-Run-Rate auf Basis des aktuellen MRR.",
    category: "Kennzahl",
    defaultCols: 3,
    allowedCols: [3, 4, 6],
    render: (data) => <ArrCard data={data} />,
  },
  {
    id: "kpi.activeMembers",
    title: "Aktive Mitglieder",
    description: "Anzahl aktiver Subscriptions inkl. Neuzugang-Delta.",
    category: "Kennzahl",
    defaultCols: 3,
    allowedCols: [3, 4, 6],
    render: (data) => <ActiveMembersCard data={data} />,
  },
  {
    id: "kpi.churnRate",
    title: "Churn-Rate (30d)",
    description: "Prozentsatz Kunden, die in den letzten 30 Tagen gekuendigt haben.",
    category: "Kennzahl",
    defaultCols: 3,
    allowedCols: [3, 4, 6],
    render: (data) => <ChurnRateCard data={data} />,
  },
  {
    id: "kpi.arpu",
    title: "ARPU",
    description: "Average Revenue per User — Durchschnitts-Umsatz je Kunde.",
    category: "Kennzahl",
    defaultCols: 3,
    allowedCols: [3, 4, 6],
    render: (data) => <ArpuCard data={data} />,
  },
  {
    id: "kpi.ltv",
    title: "LTV",
    description: "Lifetime-Value je Kunde (ARPU × erwartete Lebenszeit in Monaten).",
    category: "Kennzahl",
    defaultCols: 3,
    allowedCols: [3, 4, 6],
    render: (data) => <LtvCard data={data} />,
  },
  {
    id: "kpi.grossMargin",
    title: "Gross Margin",
    description: "Bruttomarge in Prozent.",
    category: "Kennzahl",
    defaultCols: 3,
    allowedCols: [3, 4, 6],
    render: () => <GrossMarginCard />,
  },
  {
    id: "kpi.paymentIssues",
    title: "Zahlungsprobleme",
    description: "Mitglieder mit pausierter Subscription wegen fehlgeschlagener Zahlung.",
    category: "Kennzahl",
    defaultCols: 3,
    allowedCols: [3, 4, 6],
    render: (data) => <PaymentIssuesCard data={data} />,
  },
  {
    id: "kpi.revenueTotal",
    title: "Umsatz (gefilterter Zeitraum)",
    description: "Summe Umsatz im aktuell gefilterten Zeitraum.",
    category: "Kennzahl",
    defaultCols: 3,
    allowedCols: [3, 4, 6],
    render: (data) => <RevenueTotalCard data={data} />,
  },
  {
    id: "kpi.refundRate",
    title: "Refund-Rate",
    description: "Prozentsatz erstatteter Bestellungen.",
    category: "Kennzahl",
    defaultCols: 3,
    allowedCols: [3, 4, 6],
    render: (data) => <RefundRateCard data={data} />,
  },
  {
    id: "kpi.mrrSparkline",
    title: "MRR · Mini-Sparkline",
    description: "Eine grosse Zahl + winzige Trend-Linie. Sehr platzsparend.",
    category: "Kennzahl",
    defaultCols: 3,
    allowedCols: [3, 4, 6],
    inspiration: "Sales-Overview · BOOKED SOFTWARE REVENUE",
    render: (data) => <MrrSparkline data={data} />,
  },
  {
    id: "kpi.visitorsBreakdown",
    title: "Mitglieder · Aufschluesselung",
    description: "Eine Hauptzahl mit 4 Sub-Zeilen je Depot inkl. Trend-Pfeil.",
    category: "Kennzahl",
    defaultCols: 4,
    allowedCols: [4, 6],
    inspiration: "Analytics-Dashboard · Visitors-Card",
    render: (data) => <VisitorsBreakdownCard data={data} />,
  },
  {
    id: "kpi.churnGauge",
    title: "Churn-Gauge",
    description: "Tachometer fuer Churn — visualisiert Wert vs. Ziel mit Ampel.",
    category: "Kennzahl",
    defaultCols: 4,
    allowedCols: [3, 4, 6],
    inspiration: "Sales-Overview · Cost Per Lead Gauge",
    render: (data) => <ChurnGauge data={data} />,
  },
  {
    id: "kpi.conversionGauge",
    title: "Conversion-Rate-Gauge",
    description: "Tachometer fuer Webinar→Kauf-Conversion mit Ziel-Marker.",
    category: "Kennzahl",
    defaultCols: 4,
    allowedCols: [3, 4, 6],
    render: () => <ConversionGauge />,
  },
  {
    id: "kpi.monthlyGoals",
    title: "Monats-Ziele · Plan vs. Ist",
    description: "Mehrere Progress-Bars mit Soll-Markierung. Goal-Tracking auf einen Blick.",
    category: "Kennzahl",
    defaultCols: 6,
    allowedCols: [4, 6, 8],
    inspiration: "PM-Dashboard · BUDGET-Bar geplant vs. tatsaechlich",
    render: (data) => <MonthlyGoalsProgress data={data} />,
  },

  // ─── VERLAUF ─────────────────────────────────────────────────────────────
  {
    id: "chart.revenueArea",
    title: "Umsatz-Area-Chart",
    description: "Gefuellter Flaechen-Chart fuer Umsatz/MRR-Verlauf ueber 12 Monate.",
    category: "Verlauf",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Excel-KPI · SESSIONS-Area-Chart",
    render: (data) => <RevenueAreaChart data={data} />,
  },
  {
    id: "chart.lineRevenue",
    title: "Booked-Revenue-Linie",
    description: "Reine Linien-Chart mit Datenpunkten und Werten je Punkt.",
    category: "Verlauf",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Sales-Overview · BOOKED SOFTWARE REVENUE",
    render: (data) => <LineRevenueChart data={data} />,
  },
  {
    id: "chart.verticalBars",
    title: "Aktivitaet pro Monat (Bars)",
    description: "Vertikale Bar-Chart fuer monatliche Aktivitaets-Counts.",
    category: "Verlauf",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Analytics-Dashboard · KPI trends",
    render: (data) => <VerticalBarChart data={data} />,
  },
  {
    id: "chart.groupedBars",
    title: "Revenue Vergleich (Now vs. Previous)",
    description: "Gruppierte Bars: aktueller Zeitraum neben Vergleichszeitraum je Monat.",
    category: "Vergleich",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Analytics-Dashboard · Revenue trends",
    render: (data) => <GroupedBarChart data={data} />,
  },
  {
    id: "chart.horizontalBars",
    title: "Reichweite je Kanal",
    description: "Horizontale Bars je Channel mit Vergleich gegen Vorperiode.",
    category: "Vergleich",
    defaultCols: 6,
    allowedCols: [4, 6, 8],
    inspiration: "Analytics-Dashboard · Engagement per channel",
    render: (data) => <HorizontalBarsChart data={data} />,
  },

  // ─── VERTEILUNG ──────────────────────────────────────────────────────────
  {
    id: "chart.churnDonut",
    title: "Retention vs. Churn (Donut)",
    description: "Donut mit Retention-Anteil + Legende.",
    category: "Verteilung",
    defaultCols: 4,
    allowedCols: [3, 4, 6],
    inspiration: "Excel-KPI · 88%-Optimal-Stock-Donut",
    render: (data) => <ChurnDonut data={data} />,
  },
  {
    id: "chart.productMix",
    title: "Produkt-Mix",
    description: "Donut-Pie nach Depot mit Prozent-Legende.",
    category: "Verteilung",
    defaultCols: 6,
    allowedCols: [4, 6, 8],
    inspiration: "Analytics-Dashboard · Best selling categories",
    render: (data) => <ProductMixPie data={data} />,
  },
  {
    id: "chart.statusBreakdown",
    title: "Subscription-Status",
    description: "Donut: aktive/pausierte/beendete Subscriptions.",
    category: "Verteilung",
    defaultCols: 6,
    allowedCols: [4, 6, 8],
    inspiration: "PM-Dashboard · Prozentualer Aufgabenstatus",
    render: (data) => <SubscriptionStatusBreakdown data={data} />,
  },

  // ─── FUNNEL ──────────────────────────────────────────────────────────────
  {
    id: "chart.salesFunnel",
    title: "Conversion-Funnel (Bars)",
    description: "Bars je Funnel-Step mit Conversion-Rate je Step.",
    category: "Funnel",
    defaultCols: 12,
    allowedCols: [6, 8, 12],
    render: (data) => <SalesFunnelChart data={data} />,
  },
  {
    id: "chart.funnelSteps",
    title: "Sales-Funnel (Trapez)",
    description: "Klassischer Trichter (Leads → Prospects → Opportunities → Sales).",
    category: "Funnel",
    defaultCols: 4,
    allowedCols: [3, 4, 6],
    inspiration: "Sales-Overview · Leads/Prospects/Opportunities/Sales",
    render: (data) => <FunnelStepsChart data={data} />,
  },

  // ─── TABELLE ─────────────────────────────────────────────────────────────
  {
    id: "table.cohortRetention",
    title: "Kohorten-Retention-Tabelle",
    description: "Heatmap-Tabelle: % der Anfangs-Kohorte aktiv je Folgemonat.",
    category: "Heatmap",
    defaultCols: 6,
    allowedCols: [6, 8, 12],
    render: () => <CohortRetentionTable />,
  },
  {
    id: "table.topTrades",
    title: "Top Trade-Signale",
    description: "Tabelle mit Engagement-Daten je Trade-Signal.",
    category: "Tabelle",
    defaultCols: 12,
    allowedCols: [6, 8, 12],
    render: () => <TopTradesTable />,
  },
  {
    id: "table.latestOrders",
    title: "Letzte Bestellungen",
    description: "Liste der zuletzt eingegangenen Bestellungen mit Status.",
    category: "Tabelle",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Personal-Finance-Card · Latest Income",
    render: (data) => <LatestOrdersTable data={data} />,
  },
  // ─── NEUE WIDGETS (Iteration 24, inspired by _inputs Vorlagen) ──────────

  {
    id: "kpi.churnZoneGauge",
    title: "Churn-Rate · Zone-Gauge",
    description: "Tachometer mit 3-Farben-Ampel (gruen/gelb/rot) inkl. Zeiger.",
    category: "Kennzahl",
    defaultCols: 4,
    allowedCols: [3, 4, 6],
    inspiration: "Yellowfin-BI · Whiskies/Rums KPIs",
    render: (data) => <ChurnZoneGauge data={data} />,
  },
  {
    id: "kpi.conversionZoneGauge",
    title: "Conversion · Zone-Gauge",
    description: "Tachometer fuer Conversion mit Ampel-Logik (warm/warn/cool).",
    category: "Kennzahl",
    defaultCols: 4,
    allowedCols: [3, 4, 6],
    inspiration: "Yellowfin-BI · KPIs by Product Category",
    render: () => <ConversionZoneGauge />,
  },
  {
    id: "kpi.revenueBigNumber",
    title: "Umsatz YTD · Big Number + Sparkline",
    description: "Grosser Stat + Variance-% + 12-Monats-Sparkline mit Verlaufs-Farbe.",
    category: "Kennzahl",
    defaultCols: 4,
    allowedCols: [4, 6, 8],
    inspiration: "Yellowfin-BI · Sales YTD 33,09m + Variance",
    render: (data) => <RevenueBigNumber data={data} />,
  },
  {
    id: "kpi.mrrThermometer",
    title: "MRR · Thermometer",
    description: "Vertikaler Thermometer mit Skala + Goal-Marker + verbleibender Distanz.",
    category: "Kennzahl",
    defaultCols: 4,
    allowedCols: [3, 4, 6],
    inspiration: "Sales-Overview Revenue-Slider + KPI-Slides Thermometer",
    render: (data) => <MrrThermometer data={data} />,
  },
  {
    id: "chart.yoyCompare",
    title: "Year-over-Year · Compare-Bars",
    description: "Pro Monat zwei Bars nebeneinander: Vorjahr (grau) vs. aktuelles Jahr (blau) inkl. YoY-%.",
    category: "Vergleich",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Yellowfin-BI · Sales YTD 2018 vs 2019",
    render: (data) => <YoYCompareBars data={data} />,
  },
  {
    id: "chart.targetLine",
    title: "Umsatz vs. Target · Linien-Chart",
    description: "Linie ueber Zeit + horizontale Target-Threshold; Punkte oberhalb gruen, unterhalb rot.",
    category: "Verlauf",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Yellowfin-BI · Volume Sales Versus Target",
    render: (data) => <TargetLineChart data={data} />,
  },
  {
    id: "chart.donutCenter",
    title: "Produkt-Verteilung · Donut mit Center-Stat",
    description: "Donut + grosser Gesamt-Wert in der Mitte + sortierte Legende.",
    category: "Verteilung",
    defaultCols: 6,
    allowedCols: [4, 6, 8],
    inspiration: "Yellowfin-BI · Sales by Account Segment 33m",
    render: (data) => <DonutWithCenterStat data={data} />,
  },
  {
    id: "chart.topBars",
    title: "Top-N Produkte · Horizontale Bars",
    description: "Sortierte horizontale Bars mit Rang + Name + Wert. Default Top 5.",
    category: "Vergleich",
    defaultCols: 6,
    allowedCols: [4, 6, 8],
    inspiration: "Geschaefts-KPI · Top 3 Channels by conversion",
    render: (data) => <TopProductBars data={data} />,
  },
  {
    id: "chart.miniDonutRow",
    title: "Mini-Donut-Row · Goal-Tracking je Produkt",
    description: "Eine kleine Donut je Produkt mit %-Erfuellung + Wert/Ziel-Zahl.",
    category: "Verteilung",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Yellowfin-BI · KPIs by Product Category (Whiskies/Rums)",
    render: (data) => <MiniDonutRow data={data} />,
  },

  {
    id: "table.salesPerformance",
    title: "Sales-Performance je Agent",
    description: "Vergleichstabelle: Deals, Umsatz, Conversion je Sales-Agent.",
    category: "Tabelle",
    defaultCols: 6,
    allowedCols: [4, 6, 8],
    inspiration: "Excel-KPI · Department-Vergleich",
    render: () => <SalesPerformanceTable />,
  },

  // ─── ITERATION 25: 9 weitere Widgets aus _inputs/2026-04-28-batch2 ────────

  {
    id: "kpi.areaSparklinePromo",
    title: "Area-Sparkline · Anmeldungen",
    description: "Δ% gross darueber + glattes 7-Tage-Area-Mini-Chart darunter.",
    category: "Kennzahl",
    defaultCols: 4,
    allowedCols: [3, 4, 6],
    inspiration: 'KPI-Infographics · „Promotions +45.85%"',
    render: (data) => <PromotionsAreaCard data={data} />,
  },
  {
    id: "kpi.areaSparklineRefund",
    title: "Area-Sparkline · Refund-Trend",
    description: "Δ% in Amber + Mini-Area-Chart fuer Refund-Entwicklung.",
    category: "Kennzahl",
    defaultCols: 4,
    allowedCols: [3, 4, 6],
    inspiration: 'KPI-Infographics · „Competitors +34.87%"',
    render: (data) => <CompetitorsAreaCard data={data} />,
  },
  {
    id: "kpi.metricTrioCompact",
    title: "Wachstum-Trio · Bubble-Stats",
    description: "3 farbige Kreis-Bubbles in einer Reihe — ideal fuer Δ-Werte auf einen Blick.",
    category: "Kennzahl",
    defaultCols: 6,
    allowedCols: [4, 6, 8],
    inspiration: 'KPI-Infographics · „+3.4 / +1.9 / +5.7 Bubbles"',
    render: (data) => <GrowthTrioCard data={data} />,
  },
  {
    id: "kpi.percentageRing",
    title: "Goal-Erfuellung · Percentage-Ring",
    description: "Grosser Ring mit zentralem %-Wert + Ist-/Soll-Subtitle.",
    category: "Kennzahl",
    defaultCols: 3,
    allowedCols: [3, 4, 6],
    inspiration: "Dashboard-Infographics · 65%-Ring",
    render: (data) => <GoalAchievementRing data={data} />,
  },
  {
    id: "chart.stackedVerticalBars",
    title: "Stacked Vertical Bars",
    description: "Multi-Layer-Bars pro Monat (Paid/Refunded/Open uebereinander).",
    category: "Vergleich",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Dashboard-Infographics · Mehrfarben-Stack pro Monat",
    render: (data) => <StackedVerticalBarsChart data={data} />,
  },
  {
    id: "chart.stackedHorizontalBars",
    title: "Stacked Horizontal Bars",
    description: "Pro Produkt eine Zeile mit Status-Stack (Paid + Refunded + Open).",
    category: "Vergleich",
    defaultCols: 6,
    allowedCols: [4, 6, 8, 12],
    inspiration: "Dashboard-Infographics · Multi-Layer pro Zeile",
    render: (data) => <StackedHorizontalBarsChart data={data} />,
  },
  {
    id: "chart.bubbleScatter",
    title: "Bubble-Scatter · Trade-Engagement",
    description: "X-Y-Plot mit groessenvariablen Bubbles. Visualisiert Korrelation Kommentare ↔ Views ↔ Reaktionen.",
    category: "Vergleich",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Tableau-Style Sales-Activity",
    render: (data) => <BubbleScatterChart data={data} />,
  },
  {
    id: "chart.comboBarLine",
    title: "Combo · Bars + Line",
    description: "Bestellungen als Bars + Umsatz als Linie auf demselben Chart.",
    category: "Verlauf",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Dashboard-Infographics · Bars + Line overlay",
    render: (data) => <ComboBarLineChart data={data} />,
  },
  {
    id: "chart.waterfall",
    title: "Waterfall · MRR-Bewegungen",
    description: "Start → Neue Subs → Renewals → Churn → Refunds → Ende. Macht MRR-Veraenderungen visuell sofort verstaendlich.",
    category: "Verlauf",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Power-BI Waterfall · DestinAir",
    render: (data) => <WaterfallChart data={data} />,
  },
  {
    id: "table.dealsLeaderboard",
    title: "Sales-Leaderboard",
    description: "Avatar + Rang + Name + Wert + Mini-Bar je Sales-Agent.",
    category: "Tabelle",
    defaultCols: 6,
    allowedCols: [4, 6, 8, 12],
    inspiration: "Q3-Performance · Weekly Leaderboard",
    render: () => <DealsLeaderboard />,
  },

  // ─── ITERATION 26: 7 weitere Widgets aus _inputs/2026-04-28-batch3 ────────

  {
    id: "kpi.membersQuadrant",
    title: "Mitglieder · 4-Quadranten-Karte",
    description: "4 Mini-Stats in 2x2-Grid in einer Karte (Aktiv/Pausiert/Beendet/Total).",
    category: "Kennzahl",
    defaultCols: 4,
    allowedCols: [3, 4, 6],
    inspiration: "Dark KPI-Infographic · 4 Mini-Stats (354/576/62/2348)",
    render: (data) => <MembersQuadrantCard data={data} />,
  },
  {
    id: "kpi.productTrendList",
    title: "Produkte · 30-Tage-Trend (Mini-Liste)",
    description: "Sortierte Liste mit Δ%-Badges pro Produkt. Sehr platzsparend.",
    category: "Kennzahl",
    defaultCols: 4,
    allowedCols: [3, 4, 6],
    inspiration: "Dashboards-Infographics · Title One bis Eight",
    render: (data) => <ProductTrendList data={data} />,
  },
  {
    id: "kpi.featureUsage",
    title: "Feature-Usage · Progress-Liste",
    description: "Mehrere horizontale Progress-Bars mit %-Wert pro Feature.",
    category: "Kennzahl",
    defaultCols: 6,
    allowedCols: [4, 6, 8],
    inspiration: "Dashboards-Infographics · Title-Cards mit Progress",
    render: (data) => <FeatureUsageProgress data={data} />,
  },
  {
    id: "kpi.statusStrip",
    title: "Subscription-Status · 4-Farben-Strip",
    description: "Horizontale Status-Strip-Bar mit Legende — Verteilung auf einen Blick.",
    category: "Kennzahl",
    defaultCols: 6,
    allowedCols: [4, 6, 8, 12],
    inspiration: "Highway Monitoring · 4-Farben-Statusbar",
    render: (data) => <SubscriptionStatusStrip data={data} />,
  },
  {
    id: "kpi.yoyHistory",
    title: "YoY-History · Letzte 8 Monate",
    description: "Liste mit Δ%-Werten je Monat im Vergleich zum Vorjahr (mit farbigem Border-Indicator).",
    category: "Kennzahl",
    defaultCols: 4,
    allowedCols: [3, 4, 6],
    inspiration: "Dark Theme Year-over-Year-Liste",
    render: (data) => <YoYHistoryList data={data} />,
  },
  {
    id: "chart.histogram",
    title: "Histogram · Bestellungen je Tag (30d)",
    description: "30 dichte Tages-Bars mit Highlight (bester Tag + heute) + Durchschnittslinie.",
    category: "Verlauf",
    defaultCols: 8,
    allowedCols: [6, 8, 12],
    inspiration: "Highway Monitoring + KPI-Slides Histogram",
    render: (data) => <HistogramChart data={data} />,
  },
  {
    id: "chart.churnReasonDonut",
    title: "Churn-Reasons · Donut",
    description: "Klassifizierte Churn-Gruende (Pricing/Lack of value/Non-payment/...) mit grossem Total in der Mitte.",
    category: "Verteilung",
    defaultCols: 6,
    allowedCols: [4, 6, 8],
    inspiration: 'Dark Theme „Churn Reason"-Donut',
    render: (data) => <ChurnReasonDonut data={data} />,
  },
];

export function findWidget(id: string): WidgetCatalogEntry | undefined {
  return WIDGET_REGISTRY.find((w) => w.id === id);
}
